"""event times

Revision ID: 1dc56cf1b235
Revises: f89917b18c4d
Create Date: 2018-09-27 20:04:01.259269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc56cf1b235'
down_revision = 'f89917b18c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end', sa.String(length=24), nullable=True))
    op.add_column('events', sa.Column('start', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'start')
    op.drop_column('events', 'end')
    # ### end Alembic commands ###
