"""places

Revision ID: 2dd9f66fca9e
Revises: 1dc56cf1b235
Create Date: 2018-09-27 20:42:36.466479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd9f66fca9e'
down_revision = '1dc56cf1b235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('places', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'places')
    # ### end Alembic commands ###
