"""devices

Revision ID: 645b4ebda03e
Revises: 1dddd041874e
Create Date: 2018-09-29 20:52:41.407921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645b4ebda03e'
down_revision = '1dddd041874e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=152), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
