"""devices fk

Revision ID: 9f3f70e29087
Revises: 645b4ebda03e
Create Date: 2018-09-29 21:00:22.559089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3f70e29087'
down_revision = '645b4ebda03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'owner_id')
    # ### end Alembic commands ###
